config/routes.rb
Fund33::Application.routes.draw do

  resources :users
  resources :applicants

  root to: 'static_pages#home'

  match '/home', to: 'static_pages#home'
  match '/help', to: 'static_pages#help'
  match '/submit_entry/:id', to: 'users#submit_entry', :as => 'submit_entry'

end

app/models/applicant.rb
class Applicant < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :city, :country, :phone, :email, :cv, :position
  has_attached_file :cv,
					:url => "public/system/attachments/:filename",
					:path => "public/system/attachments/:filename"		

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :city, presence: true
  validates :phone, presence: true
  validates :cv, presence: true
  validates_attachment_size :cv, :less_than => 2.megabytes, :message => 'should be less than 2MB.'	
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, 
  					uniqueness: { case_sensitive: false }				

end

app/models/country.rb
class Country < ActiveRecord::Base
  attr_accessible :iso, :name
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  attr_accessible :user_id, :question1
end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :iso, :name, :country_id
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :phone, :company, :comments,
  				  :first_name, :last_name, :city, :company_name, :website_url,
  				  :question1, :question2, :question3, :question4,
  				  :question5, :question6, :question7, :question8,
  				  :deck
  attr_accessor :updating_user

  has_attached_file :deck,
					:url => "public/system/attachments/:filename",
					:path => "public/system/attachments/:filename"	

  validates_presence_of :phone, :first_name, :last_name, :city, :company_name, :website_url,
  				  	:question1, :question2, :question3, :question4,
  					:question5, :question6, :question7, :question8,
  				  	:deck, :if => :is_updating_user?
  validates_attachment_size :deck, :less_than => 2.megabytes, :message => 'should be less than 2MB.'
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
#  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, 
#  					uniqueness: { case_sensitive: false }
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }

  private

    def is_updating_user?
      updating_user
    end

end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController

  def index
    @applicant = Applicant.new
  end

  def create
    @applicant = Applicant.new(params[:applicant])

    if @applicant.save
      UserMailer.applicant_resume(@applicant).deliver
      flash[:success] = "Thank you! We will review your application as soon as we can."
      render 'index'
    else
      flash[:error] = @applicant.errors.full_messages.to_sentence
      render 'index'
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def new
    @user = User.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @user = User.new
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    if @user.save
#      UserMailer.registration_confirmation(@user).deliver
#      flash[:success] = "Thank you! We will send you an invite when the crowdfunding campaign kicks off."
      redirect_to edit_user_path(@user)
    else
      flash[:error] = @user.errors.full_messages.to_sentence
      redirect_to root_url
    end

#    respond_to do |format|
#      if @user.save
#        format.html { redirect_to @user, notice: 'User was successfully created.' }
#        format.json { render json: @user, status: :created, location: @user }
#      else
#        format.html { render action: "new" }
#        format.json { render json: @user.errors, status: :unprocessable_entity }
#      end
#    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def submit_entry
    @user = User.find(params[:id])
    @user.updating_user = true
    if @user.update_attributes(params[:user])
      UserMailer.user_entry(@user).deliver
      flash[:success] = "Thank you for applying! We will be reaching out to your shortly for final application steps and requirements. 
                         You can reach us at support@fund33.com for any questions."
      redirect_to root_url
    else
      flash[:error] = @user.errors.full_messages.to_sentence
      render 'edit'
    end

#    respond_to do |format|
#      if @user.update_attributes(params[:user])
#        format.html { redirect_to @user, notice: 'User was successfully updated.' }
#        format.json { head :no_content }
#      else
#        format.html { render action: "edit" }
#        format.json { render json: @user.errors, status: :unprocessable_entity }
#      end
#    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper

	# attributes - general
	def make_attributes(hsh)
	  	unless hsh.nil?
	  		output = ""
	  		hsh.each {|key, val| output << "#{key}=\"#{val}\""}
	  	end
	  	output
	end

	def country_code_select(object, method, priority_countries=nil, options={}, html_options={})

	  	countries = [Country.all.collect{|r| r.name}, Country.all.collect{|r| r.name}].transpose.sort

	  	if priority_countries.nil?
	  		output = select(object, method, countries, options, html_options)
	  	else
	  		output = "<select id='#{object}_#{method}' name='#{object}[#{method}]' #{make_attributes(html_options)}>\n"
	  		output << "<option value=\"\">Country</option>" if options[:include_blank] == true

		    # get ids of priority_countries if needed
		    unless priority_countries[0].respond_to?(:id)
		     	# get ids by an array of iso codes
		     	priority_countries_ids = Country.where(:iso=>priority_countries).all
		  	else
		  		priority_countries_ids = priority_countries
		  	end

	  		priority_countries_ids.each do |pc|
	  		 	if options[:selected] == pc[:id]
	  				output << "<option value=\"#{pc[:name]}\" selected=\"selected\">#{pc[:name]}</option>"
	  			else
	  				output << "<option value=\"#{pc[:name]}\">#{pc[:name]}</option>"
	  			end	
	  		end	

		  	output << "<option value=\"0\" disabled=\"disabled\">----------------------------</option>"

		  	output << options_for_select(countries, options[:selected])
		  	output << "</select>\n"
	  	end
		output.html_safe
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/applicants/index.html.haml
.full-width-features.feature-1
  .container.contact-form.applicant-form
    .row
      .span12
        %br/
        %br/
        %h1 
          = "Application for " << (params[:position] ||= '')
        %br/
        %br/
        = form_for @applicant, :url => { :action => :create, :position => (params[:position] ||= '') }, :html => {:class => "theme-form", :multipart => true } do | f |
          .row
            .span3
              = f.text_field :first_name, :id => "first-name", :title => "First name"
            .span3
              = f.text_field :last_name, :id => "last-name", :title => "Last name"
            .span3
              = f.text_field :city, :id => "city", :title => "City"
            .span3
              %h2{:style => "text-align: left;"}
                = country_code_select(:applicant, :country,
                          priority_countries=['US','GB'],
                          {:include_blank=>true},
                          {:style=>'color: #7f7f7f; font-size: 17px; font-family: "PT Sans", Helvetica, Arial, sans-serif;'})           
          %br/
          %br/
          .row
            .span3
              = f.text_field :phone, :id => "phone", :title => "Phone"
            .span3
              = f.text_field :email, :id => "email", :title => "Email"
            .span3
              %h2{:style => "text-align: left;"}
                Upload resume: #{f.file_field :cv}

          = f.hidden_field :position, :id => "position", :title => "Position", :value => (params[:position] ||= '')
          \#{f.submit "SUBMIT!", :class => 'action-button'}

app/views/entries/new.html.erb
<h1>New user</h1>

app/views/entries/new.html.haml
%h1 Entries#new
%p Find me in app/views/entries/new.html.haml

app/views/layouts/_footer.html.erb
<div class="container">
	<div class="copyright">
		<a href="index.html" class="logo">
			<img src="assets/logo-footer.png" alt="logo">
		</a>
		<p>
			Created By <a href="#">Fund33</a>. Copyright 2013.<br>
		</p>
	</div>
</div>

app/views/layouts/_social_menu.html.erb
<!-- TOP MENU
================================================== -->
<div class="lock-header hidden-phone">
	<div class="container">
		<div class="row">
			<div class="span4 offset2">
				<h4><span>Spread the word! </span></h4>
			</div>
			<div class="span4">
				<a href="https://www.facebook.com/fund33"><img src="assets/Facebook.png" alt="Facebook"></a>
				<a href="https://twitter.com/fund33"><img src="assets/Twitter.png" alt="Twitter"></a>
				<a href="#"><img src="assets/LinkedIn.png" alt="LinkedIn"></a>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_top_menu.html.erb
<div class="top-nav">
	<span class="pull-left logo">
		<%= link_to image_tag("logo.png", :alt => "Fund33 home", :title => "Fund33 home"), root_path %>
	</span>
	<ul class="nav hidden-phone">
		<li><a href="#job" class="job-link">JOBS</a></li>
		<li><a href="#contact" class="contact-link">CONTACT</a></li>
	</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>Fund33</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>

<!-- CSS
	================================================== -->
	<link rel="stylesheet" href="/assets/bootstrap.css">
	<link rel="stylesheet" href="/assets/bootstrap-responsive.css">
	<link rel="stylesheet" href="/assets/style.css">

	<link href="http://fonts.googleapis.com/css?family=Arvo" rel="stylesheet" type="text/css">
	<link href="http://fonts.googleapis.com/css?family=PT+Sans" rel="stylesheet" type="text/css">

	<!-- Favicons
	================================================== -->
	<link rel="shortcut icon" href="/assets/favicon.ico">
	<link rel="apple-touch-icon" href="/assets/apple-touch-icon.png">
	<link rel="apple-touch-icon" sizes="72x72" href="/assets/apple-touch-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="114x114" href="/assets/apple-touch-icon-114x114.png">

	<!-- JS
	================================================== -->
	<script type="text/javascript" src="/assets/jquery.js"></script>
	<script type="text/javascript" src="/assets/jquery.easing.1.3.js"></script>
	<script type="text/javascript" src="/assets/jquery.validate.js"></script> <!-- (form validation) -->
	<script type="text/javascript" src="/assets/jquery.watermark.min.js"></script> <!-- (form filler) -->
	<script type="text/javascript" src="/assets/waypoints.min.js"></script> <!-- (sticky top menu) -->
	<script type="text/javascript" src="/assets/jquery.parallax-1.1.3.js"></script>
	<script type="text/javascript" src="/assets/theme.js"></script>  
</head>
<body>
	<% flash.each do |key, value| %>
		<%= content_tag(:div, value, class: "alert alert-#{key}") %>
	<% end %>

    <%= render 'layouts/social_menu' %>
	<%= yield %>

</body>
</html>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="page-wrapper">
	<div class="agency-wrap">
		<div class="container page-container home-container">
			<div class="row">
				<div class="span12">
					<%= render 'layouts/top_menu' %>

					<div class="header-main hidden-phone">
						<h1>&nbsp;</h1>
						<br class="hidden-phone">
						<h1>The crowdfunded product accelerator</h1>
						<h4>Build your idea through a single pledge</h4>
						<%= form_for @user, :html => {:class => "theme-form sign-up-form"}, :url => url_for(:controller => 'users', :action => 'create') do |f| %>
  						<% if @user.errors.any? %>
    						<div id="error_explanation">
    							<ul>
    								<% @user.errors.full_messages.each do |msg| %>
    								  <li>* <%= msg %></li>
    								<% end %>
    							</ul>
    						</div>
  						<% end %>
  						<%= f.text_field :email, :id => 'user-email', :placeholder => 'Enter email here' %>
  						<%= f.submit "APPLY!"%>    
						<% end %>						
					</div>

					<div class="header-main-phone visible-phone">
						<h1>The crowdfunded product accelerator</h1>
						<h4>Build your idea through a single pledge</h4>
						<%= form_for @user, :html => {:class => "theme-form sign-up-form"}, :url => url_for(:controller => 'users', :action => 'create') do |f| %>
						<% if @user.errors.any? %>
						<div id="error_explanation">
							<ul>
								<% @user.errors.full_messages.each do |msg| %>
								<li>* <%= msg %></li>
								<% end %>
							</ul>
						</div>
						<% end %>
						<%= f.text_field :email, :placeholder => 'Enter email here'  %>
						<%= f.submit "APPLY!"%>    
						<% end %>		
					</div>
				</div>
			</div>
		</div>
	</div>
	<a href="#feature-set" class="down-tab hidden-phone" name="feature-set">
		LEARN MORE <i class="arrow arrow-down">&nbsp;</i>
	</a>
	<div class="full-width-features feature-1">
		<div class="container">
			<div class="row">
				<div class="span12">
					<h1>WHAT IS FUND33?</h1>
					<h2 style="text-align: left;"><b>Have a unique idea?</b> Fund33 is a crowdfunding platform that provides a chance for products to be built through a single pledge. Simply put, we help entrepreneurs bring their ideas to life! Through a selection process, the winning entrepreneur will have their idea built out in exchange for basic equity. All selected will receive mentorship for future growth.
					</h2>
				</div>
			</div>
			<div class="row">
				<div class="span3">
					<img src="assets/process-idea.png" alt="">
					<h3>Idea</h3>
					<p>
						Create and submit a pitch deck of your unique idea.
					</p>
				</div>
				<div class="span3">
					<img src="assets/process-pledge.png" alt="">
					<h3>Pledge</h3>
					<p>
						Pledge the required dollar amount.
					</p>
				</div>
				<div class="span3">
					<img src="assets/process-selection.png" alt="">
					<h3>Selection</h3>
					<p>
						When a project is fully funded, our team will review all submissions and select the most innovative idea.
					</p>
				</div>
				<div class="span3">
					<img src="assets/process-build.png" alt="">
					<h3>Build</h3>
					<p>
						Selected winners will have their ideas fully developed with mentorship!						
					</p>
				</div>
			</div>
		</div>
	</div>
	<div class="full-width-features feature-2">
		<div class="container">
			<div class="row">

				<div class="span12">
					<h1>OUR FOCUS</h1>
					<h2 style="text-align: left;">Fund33 was founded on a simple yet, powerful idea: Empowering the next wave of entrepreneurs through development and mentorship.  Our team is made up of individuals with years of start-up experience and we love to work with people who want to disrupt the tech scene.  With that said, we do have a basic set of criteria that we use to judge and select our winners:
						<ul class="tickList">
							<li>Creativity of the idea</li>
							<li>Entrepreneur’s professional background</li>
							<li>Business model</li>
							<li>Market potential</li>
						</ul>
					</h2>
				</div>
				<div class="span12">
					<hr>
					<br>
				</div>
				<div class="span12">
					<h1>FUND33 START-UP PACKAGE</h1>
					<h2>Whether you get selected or not, your pledge won’t go to waste! All pledgers will receive a Fund33 Start-up Package. The package will include some awesome schwag and services from us and our supporting partners!</h2>
				</div>
			</div>
			<!--
			<div class="row">
				<div class="span12">
				</div>
				<div class="span12">
		            <div class="pricing-table-wrapper">
		                <div class="pricing-table row-fluid">
		                    <ul class="pricing-column span2">
		                        <li class="pricing-title">Beginner</li>
		                        
		                        <li class="pricing-price">$20 <span>/month</span>
		                        </li>
		                        
		                        <li>Yes</li>
		                        <li>Yes</li>
		                        <li>Yes</li>
		                        <li>No</li>
		                        <li>No</li>
		                        
		                        <li class="pricing-button">
		                            <a class="button" href="#">Sign Up</a>
		                        </li>
		                    </ul>
		                    
		                    <ul class="pricing-column span2">
		                        <li class="pricing-title">Beginner</li>
		                        
		                        <li class="pricing-price">$20 <span>/month</span>
		                        </li>
		                        
		                        <li>5,000MB Storage</li>
		                        <li>1TB Bandwidth</li>
		                        <li>Technical support</li>
		                        <li>cPanel &amp; MySQL</li>
		                        <li>99% uptime</li>
		                        
		                        <li class="pricing-button">
		                            <a class="button" href="#">Sign Up</a>
		                        </li>
		                    </ul>
		                    
		                    <ul class="pricing-column span3">
		                        <li class="pricing-title">Special Offer!</li>
		                        
		                        <li class="pricing-price">$50 <span>/month</span>
		                        </li>
		                        
		                        <li>50,000MB Storage</li>
		                        <li>5TB Bandwidth</li>
		                        <li>Technical support</li>
		                        <li>cPanel &amp; MySQL</li>
		                        <li>100% uptime</li>
		                        
		                        <li class="pricing-button">
		                            <a class="button" href="#">Sign Up</a>
		                        </li>
		                    </ul>
		                    
		                    <ul class="pricing-column span5">
		                        <li class="pricing-title">Special Offer!</li>
		                        
		                        <li class="pricing-price">$100 <span>/month</span>
		                        </li>
		                        
		                        <li>Unlimited Storage</li>
		                        <li>Unlimited Bandwidth</li>
		                        <li>Technical support</li>
		                        <li>cPanel &amp; MySQL</li>
		                        <li>100% uptime</li>
		                        
		                        <li class="pricing-button">
		                            <a class="button" href="#">Sign Up</a>
		                        </li>
		                    </ul>
		                </div>
		            </div>				
        		</div>
			</div>
		-->
	</div>
</div>
<div class="full-width-features feature-3">
	<div class="container">
		<div class="row">
			<div class="span12">
				<h1>MEET THE FOUNDERS</h1><br/><br/>
			</div>
			<div class="span6">
				<img src="assets/fai.png" alt="Fai Wong">
				<h3>Fai Wong, CEO</h3>
				<p>
					Fai is the development mastermind behind Fund33. With a strong career in programming and entrepreneurship, he has led several successful start-ups around the globe. Fai has the uncanny ability to make any vision come to life. No project is too large for him and he values products that disrupt existing technology. Fai is actively involved with various accelerator programs and holds a Bachelor of Computing (Software Engineering major) from Monash University.				
				</p>
			</div>
			<div class="span6">
				<img src="assets/eric.png" alt="Eric Fung">
				<h3>Eric Fung, COO</h3>
				<p>
					Eric steers the company’s growth strategy and brand. From handling operations to marketing, his battery never runs out of power.  Prior to Fund33, Eric spent his career working in both start-ups and Fortune 500 companies.  Some recent companies include EMC² and ERPLY. Eric has a passion for helping entrepreneurs and volunteering for his community.  He graduated with a degree in Advertising and Public Relations from the Pennsylvania State University.
				</p>
			</div>
		</div>
	</div>
</div>

<div class="container call-to-action">
	<!--<h1>WE'RE <br class="visible-phone"> COMING <br class="visible-phone"> SOON</h1>-->
	<a href="#top" class="scroll-top">APPLY!</a>
</div>
<div class="end_page">
	<img src="assets/33.png" alt="logo">
</div>

<div class="footer" name="contact">
	<div class="container contact-form">
		<div class="row">
			<div class="span12">
				<br>
				<br>
				<h3>Contact Us</h3>
				<div class="map"><iframe width="100%" height="250" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?ie=UTF8&amp;q=las+tablas,+madrid&amp;fb=1&amp;hq=las+tablas,&amp;hnear=0xd42287d383766c9:0xad469cc0ed50997d,Madrid,+Espa%C3%B1a&amp;cid=0,0,15011046097507982567&amp;t=m&amp;iwloc=A&amp;ll=37.786521,-122.407075&amp;spn=0.006295,0.006295&amp;output=embed"></iframe></div>
				<br>
			</div>

			<%= form_for @user, :html => {:class => "theme-form"}, :url => url_for(:controller => 'users', :action => 'create') do |f| %>
  			<% if @user.errors.any? %>
    			<div id="error_explanation">
    				<ul>
    					<% @user.errors.full_messages.each do |msg| %>
    				  	<li>* <%= msg %></li>
    					<% end %>
    				</ul>
  			</div>
  			<% end %>
  			<div class="span3">
  				<%= f.text_field :name, :id => "name-field", :title => "Name" %>
  			</div>	
  			<div class="span3">
  				<%= f.text_field :email, :id => "email-field", :title => "Email" %>
  			</div>	
  			<div class="span3">
  				<%= f.text_field :phone, :id => "phone-field", :title => "Phone" %>
  			</div>	
  			<div class="span3">
  				<%= f.text_field :company, :id => "company-field", :title => "Company" %>
  			</div>	
  			<div class="span12  comments-textarea">
  				<%= f.text_area :comments, :id => "comments-field", :title => "" %>
  			</div>	
  			<%= f.submit "SUBMIT!"%> 
			<% end %> 
		</div>
	</div>

	<div class="job-form full-width-features feature-2" name="job">
		<div class="container">
			<div class="row">
				<div class="span12">
					<br/><br/>
					<h1>CAREERS</h1>
					<h2 style="text-align: left;">Interested in joining us? We’re always looking for bright and entrepreneurial-minded people.  The best candidates are game changers, not followers!  If this sounds like you, drop us a line.Below are our current openings:
					</h2>
				</div>

				<div class="span12">
					<hr>
					<br>
				</div>
				<div class="span12">
					<h1>Global Expansion Internship Program (remote)</h1>
					<h2 style="text-align: left;">We’re looking for talented individuals to intern and grow with us.  Fund33 interns are key players with the opportunity to make big contributions.
						<ul class="tickList">
							<li>Current college student (USA or international)</li>
							<li>Interest in start-ups</li>
							<li>Completion of relevant course work and/or experience</li>
							<li>Ability to work 5-10 hours a week</li>
							<li>Driven and a self-starter</li>
							<li>Knowledge of social media, microsoft office and basic computer functions</li>
							<li>Reading &amp; writing of a second language a plus!</li>
						</ul>
					</h2>
					<%= link_to "APPLY!", applicants_path(:position => "Global Expansion Internship Program (remote)"), :class => "action-button" %>
				</div>
			</div>
		</div>
	</div>
	<%= render 'layouts/footer' %>		
</div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.haml
.full-width-features.feature-1
  .container.contact-form.apply-form
    .row
      .span12
        %br/
        %br/
        %h1 
          = "Application for Fund33"
        %br/
        %br/
        = form_for @user, :url => { :action => :submit_entry }, :html => {:class => "theme-form", :multipart => true } do | f |
          .row
            .span3
              = f.text_field :first_name, :id => "first-name", :title => "First name"
            .span3
              = f.text_field :last_name, :id => "last-name", :title => "Last name"
            .span3
              = f.text_field :city, :id => "city", :title => "City"
            .span3
              %h2{:style => "text-align: left;"}
                = country_code_select(:applicant, :country,
                          priority_countries=['US','GB'],
                          {:include_blank=>true},
                          {:style=>'color: #7f7f7f; font-size: 17px; font-family: "PT Sans", Helvetica, Arial, sans-serif;'})
          .row
            .span3
              = f.text_field :phone, :id => "phone", :title => "Phone"
            .span3
              = f.text_field :email, :id => "email", :title => "Email"
            .span3
              = f.text_field :company_name, :id => "company-name", :title => "Company name"
            .span3
              = f.text_field :website_url, :id => "website-url", :title => "Website URL"
          %hr/
          .row
            .span12{:style => "text-align: left;"}
              %br/
              = "Describe your idea in one sentence or phrase."
              = f.text_area :question1, :style => "margin-top: 10px; margin-bottom: 20px; height: 40px;"
              = "How many people are there in the team?"
              %br/
              = f.text_field :question2, :style => "margin-top: 10px; margin-bottom: 20px;"
              %br/
              = "Who are each of the founders and what are their roles in the company?"
              = f.text_area :question3, :style => "margin-top: 10px; margin-bottom: 20px; height: 40px;"
              = "What have each of the founders accomplished?"
              = f.text_area :question4, :style => "margin-top: 10px; margin-bottom: 20px; height: 40px;"
              = "Please describe your idea in detail. What is different/interesting/new about your idea?"
              = f.text_area :question5, :style => "margin-top: 10px; margin-bottom: 20px; height: 40px;"
              = "Who are your key competitors and what differentiates you?"
              = f.text_area :question6, :style => "margin-top: 10px; margin-bottom: 20px; height: 40px;"
              = "How are you going to make money?"
              = f.text_area :question7, :style => "margin-top: 10px; margin-bottom: 20px; height: 40px;"
              = "Have you raised any funds?  If yes, who has invested in your company?"
              = f.text_area :question8, :style => "margin-top: 10px; margin-bottom: 20px; height: 40px;"
              %br/
              %h2{:style => "text-align: left;"}
                Please upload a business deck/presentation: #{f.file_field :deck}
          \#{f.submit "SUBMIT!", :class => 'action-button'}

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>